language: php

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.4
          env: TARGET=test
        - php: 7.2
          env: TARGET=test COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - make start
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - make $TARGET
