language: php

services:
    - docker

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 8.0
          env: TARGET=test
        - php: 7.4
          env: TARGET=test
        - php: 7.4
          env: TARGET=test COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

install:
    - make start
    - |
      while ! curl -s -X GET http://127.0.0.1:9200/_cluster/health\?wait_for_status\=green\&timeout\=60s | grep -q '"status":"green"'
      do
        echo "==> Waiting for cluster green status" && sleep 2
      done
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - make $TARGET
